apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment  #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: dotnet-app
spec:
  replicas: 1   #The number of pods to be created in the Kubernetes cluster for the  application container
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app 
    spec:
      containers:
      - name: dotnet-app   #The name of the  application container
        image: sherifsameh/dotnet-app:latest    #The Docker image for building the application container
        ports:
        - containerPort: 80  #The port for the application container
---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-service    #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: dotnet-app
  type: NodePort  #Type of the Kubernetes Service
  ports:
  - nodePort: 30001
    protocol: TCP
    port: 80    #Service port
    targetPort: 80     #The port for the application container
