apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app 
    spec:
      containers:
      - name: dotnetserver
        image: sherifsameh/dotnet-app:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000